
[[redirects]]
  from = "/api/synthflow-proxy"
  to = "https://pohnhzxqorelllbfnqyj.supabase.co/functions/v1/start-narra-call"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"
