color: null
fieldLayouts:
  2a7f89a3-d304-44d1-8ce1-2680b2b78fdf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-16T02:57:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f7196400-1f40-4309-9c1c-4d0b95f06a47
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fd22500a-c64a-49ab-8600-bc0eeacf72f8
        userCondition: null
handle: featuresType
hasTitleField: true
icon: null
name: 'Features Type'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
