color: null
fieldLayouts:
  0c8fa947-5587-43ee-976d-6ae8be90c85e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-10T04:09:49+00:00'
            elementCondition: null
            fieldUid: f09dea28-e8c3-4256-ba3b-58ccf76f186c # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da98d665-0a0c-4fbf-a8ce-c6d5b20ee931
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-10T04:09:49+00:00'
            elementCondition: null
            fieldUid: 78f1fcef-cf25-4374-bbac-f8eecf1166e8 # Logo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17b33e35-e34a-4e1d-b83e-1f341d1ca175
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-05T23:07:31+00:00'
            elementCondition: null
            fieldUid: 1f7222cd-d88a-4f85-869a-c7fcb6ef5a3c # Hero Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa35f94d-ec9f-4dc9-b97a-461123060796
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-05T23:07:31+00:00'
            elementCondition: null
            fieldUid: 8ae67883-eb98-48b6-a508-ba9fd0588336 # Hero Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad5bc312-39b4-4552-8aab-b4e46cfa9af9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3ba526bb-2fc5-4eaf-9cd7-14750799e8e4
        userCondition: null
handle: heroImage
hasTitleField: false
icon: null
name: 'Hero Image'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
