columnSuffix: null
handle: heroDescription
instructions: null
name: 'Hero Description'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 0a9e8965-c422-4b9b-bdd0-1b80cdc3f92a # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
