defaultPlacement: end
enableVersioning: true
entryTypes:
  - cee8a391-176b-4b32-ad26-917457c0c5d8 # Features Type
handle: features
maxAuthors: 1
name: Features
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  34a8ce2a-8ab3-47db-931a-f7e1505b3dde: # narra
    enabledByDefault: true
    hasUrls: true
    template: _pages/features/entry.twig
    uriFormat: features
type: single
