defaultPlacement: end
enableVersioning: true
entryTypes:
  - 61fe53ca-1560-402d-ae94-c45c2418e176 # Default
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  34a8ce2a-8ab3-47db-931a-f7e1505b3dde: # narra
    enabledByDefault: true
    hasUrls: true
    template: _pages/home/_entry.twig
    uriFormat: __home__
type: single
